;; -*- mode: eask; lexical-binding: t -*-

(package "git-sync-mode"
         "0.5.0"
         "Automatically commit and sync local changes")

(website-url "https://github.com/justinbarclay/git-sync-mode")
(keywords "vc" "convenience")

(package-file "git-sync-mode.el")

(source "melpa")

(depends-on "emacs" "29.1")
(depends-on "async-await")

 (development
  (depends-on "ert-async")
  (depends-on "undercover")
  (depends-on "ert-runner")

  (load-paths "./test/"))
