;; -*- mode: eask; lexical-binding: t -*-

(package "git-sync-mode"
         "0.5.0"
         "Sync your git repositories on save")

(website-url "https://github.com/justinbarclay/git-sync-mode")
(keywords "vc" "convenience")

(package-file "git-sync-mode.el")

(source "melpa")

(depends-on "emacs" "30.1")
(depends-on "async-await")

(development
 (depends-on "undercover")
 (depends-on "ert-runner")

 (load-paths "./tests/"))
